### PR TITLE
fix: make save dir not having end-separator

### PR DESCRIPTION
**Pull request by gabyx**
- the save dir should not have a end separator, IMO.
- corrected the readme too.

### CODE REVIEW

**Review by MLFlexer — APPROVED** [review]
Thanks for the PR!
1. Have you tested this locally?

2. Out of curiosity is it convention or useful in some way to not have the end-seperator?
I am myself not aware of any reasons other than stylistic reasons, but maybe there is more to it?
Either way, I would not mind merging this as I don't really have an opinion for when to have or not have the endning seperator in directories

**Comment by gabyx** [comment]
Its a convention.
And just weird. The PR does not work currently as there are more cases where you do some regex/sub or prefix removal which now does not work anymore.

**Comment by gabyx** [comment]
You can have the end separator internally, but I would not suggest, and make the API that it is agnostic to end separator ...

**Comment by MLFlexer** [comment]
Closing as it is not fixed, but opened #76 to eventually fix

**Pull request closed without merging**
